CREATE TABLE Employee (NIK varchar(7) NOT NULL, Name varchar(50) NOT NULL, Email varchar(20) NOT NULL, Position varchar(20) NOT NULL, Password varchar(20) NOT NULL, PRIMARY KEY (NIK)) type=InnoDB;
CREATE TABLE Team_project (TeamProject_ID varchar(12) NOT NULL, NIK varchar(7) NOT NULL, Project_ID varchar(12) NOT NULL, Job_ID char(2) NOT NULL, Task_ID varchar(12) NOT NULL, PRIMARY KEY (TeamProject_ID)) type=InnoDB;
CREATE TABLE Project (Project_ID varchar(12) NOT NULL, Customer_ID varchar(12) NOT NULL, Project_Name varchar(50) NOT NULL, Project_Mandays int(10) NOT NULL, Project_StartDate date NOT NULL, Project_EndDate date NOT NULL, Project_Status char(1) NOT NULL, PRIMARY KEY (Project_ID)) type=InnoDB;
CREATE TABLE Client (Client_ID varchar(12) NOT NULL, Client_Name varchar(20) NOT NULL, Client_Address varchar(100) NOT NULL, Client_Email varchar(50) NOT NULL, PRIMARY KEY (Client_ID)) type=InnoDB;
CREATE TABLE Notification (Notif_ID varchar(12) NOT NULL, NIK varchar(7) NOT NULL, Notif_Name varchar(20) NOT NULL, Notif_Desc varchar(100) NOT NULL, Notif_Date date NOT NULL, PRIMARY KEY (Notif_ID)) type=InnoDB;
CREATE TABLE Task (Task_ID varchar(12) NOT NULL, Project_ID varchar(12) NOT NULL, Category_ID char(1) NOT NULL, TeamProject_ID varchar(12) NOT NULL, Task_StartDate date NOT NULL, Task_EndDate date NOT NULL, Task_Target date NOT NULL, Task_Name varchar(20) NOT NULL, Task_Status char(1) NOT NULL, Task_Document_No varchar(20) NOT NULL, Task_Notes varchar(200) NOT NULL, PRIMARY KEY (Task_ID)) type=InnoDB;
CREATE TABLE Category (Category_ID char(1) NOT NULL, Category_Name varchar(20) NOT NULL, Category_Desc varchar(100) NOT NULL, PRIMARY KEY (Category_ID)) type=InnoDB;
CREATE TABLE Status (Status_ID char(1) NOT NULL, Status_Name varchar(20) NOT NULL, Status_Desc varchar(100) NOT NULL, PRIMARY KEY (Status_ID)) type=InnoDB;
CREATE TABLE Document (Document_No varchar(20) NOT NULL, Document_Name varchar(50) NOT NULL, Document_Desc varchar(100) NOT NULL, Document_URL varchar(100) NOT NULL, Document_Status varchar(10) NOT NULL, PRIMARY KEY (Document_No)) type=InnoDB;
CREATE TABLE Job (Job_ID char(2) NOT NULL, Job_Name varchar(30) NOT NULL, Job_Desc varchar(50) NOT NULL, PRIMARY KEY (Job_ID)) type=InnoDB;
CREATE TABLE AuditTrail (AuditTrail_ID varchar(10) NOT NULL, Audit_Activity varchar(50) NOT NULL, Audit_Field varchar(20) NOT NULL, Audit_Before varchar(50) NOT NULL, Audit_After varchar(50) NOT NULL, Audit_Date date NOT NULL, Audit_Time time NOT NULL, Audit_User varchar(7) NOT NULL) type=InnoDB;
CREATE TABLE Problem_Log (PRL_ID int(10), PRL_Name int(10), PRL_Description int(10), `PRL StartDate` int(10), `Column` int(10)) type=InnoDB;
CREATE TABLE PRL (PRL_ID varchar(12) NOT NULL, Task_ID varchar(12) NOT NULL, PRL_Name varchar(50) NOT NULL, PRL_Desc int(100) NOT NULL, PRL_StartDate date NOT NULL, PRL_EndDate date NOT NULL, PRL_Target date NOT NULL, PRL_Status char(1) NOT NULL, PRL_Notes varchar(200) NOT NULL, PRL_Document_No varchar(20) NOT NULL) type=InnoDB;
ALTER TABLE Project ADD CONSTRAINT FKProject664944 FOREIGN KEY (Project_Status) REFERENCES Status (Status_ID);
ALTER TABLE Task ADD CONSTRAINT FKTask857121 FOREIGN KEY (Task_Status) REFERENCES Status (Status_ID);
ALTER TABLE Project ADD CONSTRAINT FKProject820043 FOREIGN KEY (Customer_ID) REFERENCES Client (Client_ID);
ALTER TABLE Task ADD CONSTRAINT FKTask390397 FOREIGN KEY (Task_Document_No) REFERENCES `Document ` (Document_No);
ALTER TABLE Task ADD CONSTRAINT FKTask885393 FOREIGN KEY (Category_ID) REFERENCES Category (Category_ID);
ALTER TABLE Notification ADD CONSTRAINT FKNotificati823642 FOREIGN KEY (NIK) REFERENCES Employee (NIK);
ALTER TABLE Team_project ADD CONSTRAINT FKTeam_proje214919 FOREIGN KEY (NIK) REFERENCES Employee (NIK);
ALTER TABLE Team_project ADD CONSTRAINT FKTeam_proje153194 FOREIGN KEY (Project_ID) REFERENCES Project (Project_ID);
ALTER TABLE Team_project ADD CONSTRAINT FKTeam_proje756887 FOREIGN KEY (Job_ID) REFERENCES Job (Job_ID);
ALTER TABLE PRL ADD CONSTRAINT FKPRL502490 FOREIGN KEY (Task_ID) REFERENCES Task (Task_ID);
ALTER TABLE Team_project ADD CONSTRAINT FKTeam_proje910071 FOREIGN KEY (Task_ID) REFERENCES Task (Task_ID);
ALTER TABLE PRL ADD CONSTRAINT FKPRL68957 FOREIGN KEY (PRL_Status) REFERENCES Status (Status_ID);
ALTER TABLE PRL ADD CONSTRAINT FKPRL165152 FOREIGN KEY (PRL_Document_No) REFERENCES `Document ` (Document_No);
ALTER TABLE PRL ADD CONSTRAINT FKPRL165153 FOREIGN KEY (PRL_Document_No) REFERENCES `Document ` (Document_No);
